
keepvar <- c(
	"patientid", "visitnum",
	"dateofbirth", "sex", "age", "dateofdeath",
	"visitdate", "visittypecode",
	"cd4", "cd4percent",
	"hf_type", "hf_own",
	"weight", "heightm",
	"hb",
	"alt",
	"whostage",
	"functionalstatuscode",
	"arvadherencecode", "arvstatuscode", "arvreasoncode", "arvcode",
	"tbstatuscode", "tbscreeningid", "tbrxiptid",
	"nutritionalsupport", "nutritionalstatusid",
	"nutritionalsupplementid",
	"appointmentdate",
	"status_orig",
	"minage", "maxage",
	"bmi",
	"lastvisitdate",
	"arts_first_date", "artstart", "age_artstart",
	"artyear",
	"testtypeid",
	"resdate",
	"enrol_age", "enrol_date", "enrol_year",
	"ctx",
	"referredfromid",
	"enrol_cd4", "enrol_weight", "enrol_whostage",
	"enrol_hf_type", "enrol_referredfromid",
	"enrol_cd4percent", "enrol_ctx",
	"elig",
	"enrol_agem",
	"startdate",
	"startyear",
	"starttimem",
	"starttimecat",
	"start_cd4",
	"start_weight",
	"start_whostage",
	"start_hf_type",
	"start_referredfromid",
	"start_cd4percent",
	"start_ctx",
	"start_age",
	"birthyear",
	"death",
	"status",
	"statusdate"
)

c_visits <- c_visits[keepvar]
